### ISSUE TITLE
$dispatch is not a function error

### ISSUE THREAD

**Issue by sdpollack** [lilasquared/use-dotnetify#1]
See https://github.com/dsuryd/dotNetify/issues/199

Dicky Suryadi suggested I ask about this here.

---

I'm using dotNetify with use-netify and React hooks. I am receiving client updates fine, but now I'm trying to add updates to the server and I'm getting "TypeError: vm.$dispatch is not a function" error.

Here is some of the code:

  
import React, { Fragment } from 'react'
...
import dotnetify  from "dotnetify";
import useDotnetify from "use-dotnetify";

const unitList = require('../FakeData/FakeUnits.json')

  const [values, setValues] = React.useState({
    myVar: 'myvalue',
  })

  function handleChange(event) {
    setValues((oldValues) => ({
      ...oldValues,
      [event.target.name]: event.target.value,
    }))
    vm.$dispatch(values);
  }

  const initialState = {
    myVar: '',
    AssetViewData: [],
    unitName: "",
  };

  const vm = useDotnetify("myVMController", initialState);
...

  <form className={classes.root} autoComplete='off'>
    <FormControl className={classes.formControl}>
      <InputLabel ref={inputLabel} shrink htmlFor='unit-label-placeholder'>
        Unit
      </InputLabel>
      <Select
        value={values.unitName}
        key={values.unitId}
        onChange={handleChange}
        displayEmpty
        input={<Input name='unitName' id='unit-label-placeholder' />}
        name='unitName'
        className={classes.selectEmpty}
      >
        {unitList.map((units) => (
          <MenuItem value={units.unitName}>{units.unitName}</MenuItem>
        ))}
      </Select>
    </FormControl>
  </form>

**Comment by lilasquared** [comment]
Currently the vm is not returned from useDotnetify, just the state.  Let me see if i can tweak it to return the vm and I'll get back to you.

**Comment by lilasquared** [comment]
@sdpollack I have been tied up and haven't looked at this yet.  Have you taken a crack at it? Fancy submitting a PR?

**Comment by sdpollack** [comment]
@lilasquared  I'm a very junior developer and I don't yet have the skills to dig into the internals of dotNetify.  I was hoping it would be a timesaver for me on our React Hooks project, but that has not turned out to be the case.  I've moved on from dotNetify and am using SignalR directly.  Thanks for your assistance.

**Comment by lilasquared** [comment]
ah alrighty then, sorry I couldn't be more help!
