### ISSUE TITLE
Add the ability to call $dispatch by returning vm and not just the state

### ISSUE THREAD

**Issue by dkorth** [lilasquared/use-dotnetify#2]
Please add $dispatch so I can make queries with input params. I believe that means returning the vm and not just the state. This would be awesome, otherwise I don't know when I'd even use use-dotnetify because I always need to be able to pass in parameters to my queries.

**Comment by lilasquared** [comment]
@dkorth would you mind taking a look at the PR and maybe testing out the code to see if this will work for you?  I haven't yet tested passing full actions but I exposed the full vm.

**Comment by dkorth** [comment]
Yep, I'll test it tonight.

Dewayne Korth
(303) 710-5912
Get Outlook for Android<https://aka.ms/ghei36>




On Wed, Aug 14, 2019 at 5:08 PM -0600, "Aaron Roberts" <notifications@github.com<mailto:notifications@github.com>> wrote:


@dkorth<https://github.com/dkorth > would you mind taking a look at the PR and maybe testing out the code to see if this will work for you? I haven't yet tested passing full actions but I exposed the full vm.

**Comment by dkorth** [comment]
I tested it and it worked perfectly. Should make some fully encapsulated functional components possible with the use of hooks.

Thanks!
Dewayne Korth
Senior Software Architect
(720) 749-6412 Direct
(303) 710-5912 Mobile

BLUEFIN, LLC
Improving Facility Performance
bluefinllc.com

**Comment by lilasquared** [comment]
@dkorth I did some testing of my own and made some adjustments.  I'll push them up soon.  It does affect the api a bit which allows for more accessing more than one model within an app

**Comment by lilasquared** [comment]
@dkorth use-dotnetify 2.0.0 was just published, see readme for usage.  Its slightly different than before but relatively the same.  Let me know how it works out for you!
